/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from '@stencil/core/internal';


export namespace Components {
  interface SmartComplete {
    'backend': string;
    'limit': number;
    'throttle': number;
  }
}

declare global {


  interface HTMLSmartCompleteElement extends Components.SmartComplete, HTMLStencilElement {}
  var HTMLSmartCompleteElement: {
    prototype: HTMLSmartCompleteElement;
    new (): HTMLSmartCompleteElement;
  };
  interface HTMLElementTagNameMap {
    'smart-complete': HTMLSmartCompleteElement;
  }
}

declare namespace LocalJSX {
  interface SmartComplete {
    'backend'?: string;
    'limit'?: number;
    'throttle'?: number;
  }

  interface IntrinsicElements {
    'smart-complete': SmartComplete;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'smart-complete': LocalJSX.SmartComplete & JSXBase.HTMLAttributes<HTMLSmartCompleteElement>;
    }
  }
}


